import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GlobalErrorLogger } from "@/components/global-error-logger";
import { TooltipProvider } from "@/components/ui/tooltip";
import "./globals.css";

// Change the font here: next/font/google has Inter, DM_Sans, Plus_Jakarta_Sans, Outfit, etc.
// https://nextjs.org/docs/app/building-your-application/optimizing/fonts
const fontSans = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontSans.variable} font-sans antialiased`}>
        <GlobalErrorLogger />
        <TooltipProvider>{children}</TooltipProvider>
      </body>
    </html>
  );
}
